config/routes.rb
RuoteOnRails::Application.routes.draw do

  resources :workitems
  resources :processes
  resources :forms
  resources :definitions

  # ruote-kit
  #
  match '/_ruote' => RuoteKit::Application
  match '/_ruote/*path' => RuoteKit::Application

  # login / logout
  #
  resources :sessions
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  # /
  #
  root :to => 'workitems#index'
end

app/models/definition.rb
class Definition < ActiveRecord::Base

  def name

    tree[1]['name'] || tree[1].find { |k, v| v.nil? }.first
  end

  def revision

    tree[1]['revision']
  end

  def tree

    Ruote::Reader.read(definition)
  end

  def tree_json

    Rufus::Json.encode(tree)
  end

  # Makes sure the 'definition' column contains a string that is Ruby code.
  #
  def rubyize!

    self.definition = Ruote::Reader.to_ruby(tree).strip
  end
end

app/models/form.rb
class Form < ActiveRecord::Base

  def match(workitem)

    task = task_regex.index('|') ?
      "#{workitem.participant_name}|#{workitem.task}" :
      workitem.task

    (Regexp.new(task_regex[1..-2]).match(task) != nil)
  end

  def self.for(workitem)

    all.find { |form| form.match(workitem) }
  end
end

app/models/user.rb
#
# This is a very simple User model, ready to be torn off and replaced by
# another mechanism / library, like for example :
#
#   http://github.com/hassox/warden/
#

require 'bcrypt'


#
# User information is stored in config/passwd
#
#   username:locale:pass_bcrypted:groupa,groupb
#
class User

  attr_reader :name
  attr_reader :locale
  attr_reader :pass
  attr_reader :groups

  def initialize(name, locale, pass, groups)

    @name = name
    @locale = locale
    @pass = pass
    @groups = groups
  end

  def in_group?(group_name)

    @groups.include?(group_name)
  end

  def admin?

    in_group?('admin')
  end

  def self.admin?(name)

    if u = find(name)
      u.admin?
    else
      false
    end
  end

  def self.find(name)

    all.find { |u| u.name == name }
  end

  def self.authentify(user, pass)

    all.each do |u|
      next unless u.name == user
      return u if u.pass == pass
    end

    nil
  end

  def self.all

    fn = Rails.root.join('config', "password.#{Rails.env}")
    fn = File.exist?(fn) ? fn : Rails.root.join(*%w[ config password ])

    lines = File.readlines(fn)

    lines.inject([]) { |a, line|

      line = line.strip

      if line.length > 0 && ( ! line.match(/^#/))

        name, locale, password, groups = line.split(':')
        password = BCrypt::Password.new(password)
        groups = (groups || '').split(',')

        a << User.new(name, locale, password, groups)
      end

      a
    }
  end

  # Returns a list of all the known groups (all the groups mentioned in
  # the passwd file).
  #
  def self.groups

    all.collect { |user| user.groups }.flatten.uniq.sort
  end
end

app/models/workitem.rb
#
# Simply opening the ruote workitem class to add some things specific
# to arts (and ActiveModel).
#
class Ruote::Workitem

  #include ActiveModel::Naming
  #include ActiveModel::Validations

  def task
    params['task']
  end

  def participant_name=(name)
    @h['participant_name'] = name
  end

  def self.for_user(username)

    user = User.find(username)

    return RuoteKit.engine.storage_participant.all if user.admin?

    # note : ruote 2.1.12 should make it possible to write
    #
    #   RuoteKit.engine.storage_participant.by_participant(
    #     [ username, user.groups, 'anyone' ].flatten)
    #
    # directly.

    [ username, user.groups, 'anyone' ].flatten.collect { |pname|
      RuoteKit.engine.storage_participant.by_participant(pname)
    }.flatten
  end

  #--
  # active model (method need to make of workitems active models)
  #++

#  def self.model_name
#
#    return @_model_name if @_model_name
#
#    mn = Object.new
#    def mn.name; 'workitem'; end
#    @_model_name = ActiveModel::Name.new(mn)
#  end
#
#  def to_model
#    self
#  end
#
#  def destroyed?
#    fields['_destroyed'] == true
#  end
#
#  def new_record?
#    @h['fei'] == {}
#  end
#
#  def persisted?
#    @h['fei'] != {}
#  end
#
#  def to_key
#    return nil unless persisted?
#    [ @h['_id'] ]
#  end

  def to_param
    fei.sid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_filter :login_required

  layout 'application'

  protected # if it makes any sense

  def login_required

    return true if self.class == SessionsController
      # no login required for the login/logout screens

    return true if session[:username]

    redirect_to :controller => 'sessions', :action => 'new'
    false
  end
end

app/controllers/definitions_controller.rb
#
# process definitions
#
class DefinitionsController < ApplicationController

  def index

    @definitions = Definition.all
  end

  def new

    @definition = Definition.new
    @definition.definition = %{
Ruote.process_definition 'my first definition' do
  sequence do
    alice
    bob
  end
end
    }

    render :action => 'edit'
  end

  def edit

    @definition = Definition.find(params[:id])
  end

  def show

    @definition = Definition.find(params[:id])
  end

  def create

    definition = Definition.new(params[:definition])
    definition.rubyize!
    definition.save!

    redirect_to :action => 'index'
  end

  def update

    definition = Definition.find(params[:id])
    definition.attributes = params[:definition]
    definition.rubyize!
    definition.save!

    redirect_to :action => 'index'
  end
end

app/controllers/forms_controller.rb
#
# quaderno forms
#
class FormsController < ApplicationController

  def index

    @forms = Form.all
  end

  def new

    @form = Form.new

    @form.task_regex = '/clean the car/'
    @form.template = %{
box fields
  text_input .name "name"
  text_input .age "age"
  text_input .color "colour"
    }.strip
    @form.sample_data = Rufus::Json.encode({
      'fields' => {}
    })

    render :action => 'show'
  end

  def show

    @form = Form.find(params[:id])
  end

  def create

    Form.new(params[:form]).save!

    redirect_to :action => 'index'
  end

  def update

    form = Form.find(params[:id])
    form.attributes = params[:form]
    form.save!

    redirect_to :action => 'index'
  end
end

app/controllers/processes_controller.rb
#
# ruote process instances
#
class ProcessesController < ApplicationController

  def index

    @processes = RuoteKit.engine.processes
  end

  def create

    definition = Definition.find(params[:definition])

    wfid = RuoteKit.engine.launch(definition.definition)

    flash[:notice] = I18n.t('flash.notice.launched', :wfid => wfid)

    redirect_to :controller => 'definitions', :action => 'index'
  end
end

app/controllers/sessions_controller.rb
#
# dummy session/login management
#
class SessionsController < ApplicationController

  def new

    # simply letting app/sessions/new.haml get shown
  end

  def create

    if u = User.authentify(params[:username], params[:password])
      session[:username] = params[:username]
      session[:locale] = u.locale
      redirect_to '/'
    else
      flash[:error] = I18n.t('flash.errors.login_failed')
      render :action => :new
    end
  end

  def destroy

    session.delete(:username)
      # logging out

    render :action => :new
  end
end

app/controllers/workitems_controller.rb
#
# ruote workitems
#
class WorkitemsController < ApplicationController

  def index

    @workitems = Ruote::Workitem.for_user(session[:username])
  end

  def show

    @workitem =
      RuoteKit.storage_participant[params[:id]]
    @tree =
      Rufus::Json.encode(RuoteKit.engine.process(@workitem.wfid).current_tree)
    @form =
      Form.for(@workitem)
  end

  def update

    fields = Rufus::Json.decode(params[:workitem][:fields])

    workitem = RuoteKit.storage_participant[params[:id]]
    workitem.fields.merge!(fields)

    submit = params[:workitem][:submit]

    if submit == 'proceed'

      RuoteKit.storage_participant.reply(workitem)

      flash[:notice] = I18n.t('flash.notice.proceeded', :fei => workitem.fei.sid)
    else

      if submit == 'release'
        workitem.participant_name = 'anyone'
      elsif submit == 'take'
        workitem.participant_name = session[:username]
      end

      RuoteKit.storage_participant.update(workitem)
    end

    redirect_to :action => :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/definitions/edit.haml
%h1
  = t '.title'

= form_for @definition do |f|

  #flow
    %canvas#fluo{ :width => 200, :height => 200 }
  
  #editor
    %div.tab
      %a{ :href => '', :onclick => 'return show("#textbox")'} #{t('.textbox')}
    #fluo_editor

  #textbox
    %div.tab
      %a{ :href => '', :onclick => 'return show("#editor")'} #{t('.editor')}
    = f.text_area :definition

  .buttons
    = link_to t('.cancel'), :action => :index
    = f.submit t('.submit')

:javascript

  $('#textbox').hide();

  //
  // show

  function show(id) {
    $('#editor').hide();
    $('#textbox').hide();
    $(id).show();
    return false;
  }

  //
  // editor

  FluoEditor.renderFlow('fluo_editor', #{@definition.tree_json});

  $('#fluo_editor')[0].onChange = function (tree) {
    Fluo.renderFlow('fluo', tree);
    Fluo.crop('fluo');
  }
  $('#fluo_editor')[0].onOver = function (expid) {
    Fluo.highlight('fluo', expid);
  }

  $('#definition_submit').bind('click', function() {
    if ($('#editor')[0].style.display === 'none') return;
    $('#definition_definition').val(FluoEditor.asJson('fluo_editor'));
  });

  //
  // fluo

  document.getElementById('fluo').noOuterBorder = true;
  
  Fluo.renderFlow('fluo', #{@definition.tree_json})
  Fluo.crop('fluo');

app/views/definitions/index.haml
%h1
  = t '.title'

%table.list

  %thead
    %td
      = t 'definition.id'
    %td
      = t 'definition.name'
    %td
      = t 'definition.revision'
    %td

  - @definitions.each do |definition|
    %tr
      %td
        = definition.id
      %td
        = definition.name
      %td
        = definition.revision
      %td
        = link_to t('.show'), definition_path(definition)
        = link_to t('.edit'), edit_definition_path(definition)

.buttons
  %a.button{ :href => new_definition_path }
    = t('.new')

app/views/definitions/show.haml
%h1
  = t '.title'

#flow
  %canvas#fluo{ :width => 200, :height => 200 }

%pre#definition #{@definition.definition}

.buttons
  = link_to t('.back'), :action => :index
  = button_to t('.launch'), processes_path(:definition => @definition.id)


:javascript

  document.getElementById('fluo').noOuterBorder = true;
  
  Fluo.renderFlow('fluo', #{@definition.tree_json})
  Fluo.crop('fluo');

app/views/forms/index.haml
%h1
  = t '.title'

%table.list

  %thead
    %td
      = t 'form.id'
    %td
      = t 'form.task_regex'
    %td

  - @forms.each do |form|
    %tr
      %td
        = form.id
      %td
        = form.task_regex
      %td
        = link_to t('.show'), form_path(form)

.buttons
  %a.button{ :href => new_form_path }
    = t('.new')

app/views/forms/show.haml
%h1
  = t('.title')

= form_for @form do |f|

  %table.form

    %tr
      %td
        = t('form.task_regex') + ':'
        = f.text_field :task_regex
      %td

    %tr
      %td
        = t('.template') + ':'
        %div
          = f.text_area :template
        .buttons.right
          %a{ :href => '', :onclick => 'return render();' }
            = t('.render')
      %td
        = t('.form') + ':'
        #quad.quad_root
        .buttons
          %a{ :href => '', :onclick => 'return undo();' }
            = t('.undo')
          %a{ :href => '', :onclick => 'return reset();' }
            = t('.reset')
          %a{ :href => '', :onclick => 'return produce();' }
            = t('.produce')

    %tr
      %td
        = t('.data_in') + ':'
        %div
          = f.text_area :sample_data, :rows => 10
        -# #data_in.jagaimo
      %td
        = t('.data_out') + ':'
        #data_out.jagaimo

  .buttons
    = link_to t('.cancel'), :action => :index
    = f.submit t('.submit')


:javascript

  //var data_in = JSON.parse('#{@form.sample_data}');
  //Jagaimo.render('#data_in', data_in, { mode: 'tree' });

  function render () {
    try {
      var data = JSON.parse($('#form_sample_data')[0].value);
      var template = Quaderno.parse($('#form_template')[0].value);
      Quaderno.render('#quad', template, data);
    }
    catch (e) {
    }
    return false;
  }

  render();

  function undo () {
    Quaderno.undo('#quad');
    return false;
  }
  function reset () {
    Quaderno.reset('#quad');
    return false;
  }

  function produce () {

    var product = Quaderno.produce('#quad');
    Jagaimo.render('#data_out', product, { mode: 'tree' });

    return false;
  }

app/views/layouts/application.haml
%html

  %head

    %meta( http-equiv="Content-Type" content="text/html; charset=UTF-8" )

    %title ruote-on-rails

    %link( href='/images/favicon.png' type='image/png' rel='icon' )
    %link{ :href => '/stylesheets/reset.css', :type => 'text/css', :rel => 'stylesheet' }
    %link{ :href => '/stylesheets/ruote-fluo-editor.css', :type => 'text/css', :rel => 'stylesheet' }
    %link{ :href => '/stylesheets/quaderno.css', :type => 'text/css', :rel => 'stylesheet' }
    %link{ :href => '/stylesheets/jagaimo.css', :type => 'text/css', :rel => 'stylesheet' }
    %link{ :href => '/stylesheets/ruote-on-rails.css', :type => 'text/css', :rel => 'stylesheet' }

    /[if !IE7]
      :css
        .container { display: table; height: 100%; }

    %script{ :src => '/javascripts/jquery-1.4.3.min.js' }
    %script{ :src => '/_ruote/javascripts/ruote-fluo.js' }
    %script{ :src => '/_ruote/javascripts/ruote-fluo-editor.js' }
    %script{ :src => '/javascripts/quaderno.js' }
    %script{ :src => '/javascripts/jagaimo.js' }

  %body

    .container

      .header
        %a.home{ :href => '/' }
          %img{ :src => '/images/ruote.png', :alt => 'ruote-on-rails' }
          
      - if session[:username]
        %a.button.user{ :href => '/logout' } #{t('.logout')} #{session[:username]}
        .nav
          %ul
            %li
              = link_to t('.workitems'), workitems_path
            %li
              = link_to t('.processes'), processes_path
            %li
              = link_to t('.forms'), forms_path
            %li
              = link_to t('.definitions'), definitions_path
            - if User.admin?(session[:username])
              %li
                = link_to t('.ruote'), '/_ruote'

      = render :partial => 'shared/flash'

      .main_content
        = yield :layout

    .footer
      %p
        powered by
        %a{ :href => 'http://ruote.rubyforge.org' }
          ruote
        and
        %a{ :href => 'http://github.com/tosch/ruote-kit' }
          ruote-kit

app/views/processes/index.haml
%h1
  = t '.title'

%table.list

  %thead
    %td
      = t 'process.wfid'
    %td
      = t 'process.size'
    %td
      = t 'process.position'

  - @processes.each do |process|
    %tr
      %td
        = process.wfid
      %td
        = process.expressions.size
      %td
        - process.position.each do |pos|
          - fei, pname, info = pos
          = "#{pname} #{info['task']}"

app/views/shared/_flash.haml
#flashes
  - %w[ notice error ].each do |key|
    - if f = flash()[key.intern]
      %div{ :class => key }
        = f

app/views/workitems/index.haml
%h1
  = t '.title'

%table.list

  %thead
    %td
      = t 'workitem.id'
    %td
      = t 'workitem.participant_name'
    %td
      = t 'workitem.task'
    %td

  - @workitems.each do |workitem|
    %tr
      %td
        = workitem.fei.sid
      %td
        = workitem.participant_name
      %td
        = workitem.params['task']
      %td
        = link_to t('.show'), workitem_path(workitem)

app/views/workitems/show.haml
%h1
  = t '.title'

#flow
  %canvas#fluo{ :width => 1150, :height => 700 }

#form

  - form_tag(workitem_path(@workitem), :method => 'PUT') do

    = hidden_field_tag 'workitem[submit]', 'save'

    - if @form

      #quad.quad_root

      = hidden_field_tag 'workitem[fields]', Rufus::Json.encode(@workitem.fields)

    - else

      %div #{t('.fields') + ':'}
      = text_area_tag 'workitem[fields]', Rufus::Json.encode(@workitem.fields), :rows => 10, :cols => 77

    .buttons

      = link_to t('.cancel'), :action => :index

      - if @workitem.participant_name != 'anyone'
        = submit_tag t('.release'), :id => 'release_button'
      - else
        = submit_tag t('.take'), :id => 'take_button'

      = submit_tag t('.save'), :id => 'save_button'
      = submit_tag t('.proceed'), :id => 'proceed_button'


:javascript

  $('#release_button').bind('click', function() {
    $('#workitem_submit').val('release');
    return true;
  });
  $('#take_button').bind('click', function() {
    $('#workitem_submit').val('take');
    return true;
  });
  $('#proceed_button').bind('click', function() {
    $('#workitem_submit').val('proceed');
    return true;
  });

  //
  // fluo

  document.getElementById('fluo').noOuterBorder = true;
  
  Fluo.renderFlow(
    'fluo', #{@tree}, { workitems: [ '#{@workitem.fei.expid}' ] });
  
  Fluo.crop('fluo');

- if @form

  :javascript

    //
    // quad

    var data = JSON.parse($('#workitem_fields')[0].value);
    var template = Quaderno.parse(#{@form.template.inspect});
    Quaderno.render('#quad', template, data);

    var produce = function() {
      var product = JSON.stringify(Quaderno.produce('#quad'));
      $('#workitem_fields').val(product);
      return true;
    };

    $('#save_button').bind('click', produce);
    $('#proceed_button').bind('click', produce);